### ISSUE TITLE
Fixture load Alternatives

### ISSUE THREAD

**Issue by BransonGitomeh** [arryon/sails-hook-fixtures#10]
can i load fixtures using other methods other than the ones stated on the read me?

ie on a file or anywhere

```
module.exports = {
//fixture stuff here

}
```

instead of having a file, this will allow for greater flexibility as to where the assosiations are stored and can even be stored across multiple files per waterline collection,also opens up usage to other areas waterline is used outside sails

**Comment by arryon** [comment]
Hi,

In principe the fixtures are only defined for sails' usage via local.js. module.exports.fixtures defines the fixtures to be loaded, so you are free to add your own loader as export definition:

```javascript
/i.e. sails.config.fixtures.js
module.exports = {
 loadFixtures: function () {
    return {
      //define your fixtures
    };
  };
}

//in sails.config.local.js
var fixtures = require('./fixtures');
module.exports = {
  fixtures: fixtures.loadFixtures();
};
```

Second, if you want to use the module outside of sails, unfortunately this is not supported. If you look at lib/index.js, the file is explicitly modeled to act as a Sails hook (according to http://sailsjs.org/documentation/concepts/extending-sails/hooks/installable-hooks). The easiest way to decouple the package from Sails would be to create a new NPM package solely for the waterline functionality, and include it as dependency in this module. It would require a major rewrite of index.js as you need to interface with the Waterline models in a different way. Right now I don't have time or incentive to implement this, so your best bet would be to fork the repo yourself.

Is this helpful in any way?

**Comment by arryon** [comment]
Since I've not gotten a response back, I'll assume the answer was sufficient, therefore closing this issue.
